### ISSUE TITLE
Initialization Failure in Kubernetes: ‘Cannot assign requested address (os error 99)’ with Fuel-core

### ISSUE THREAD

**Issue by wengych** [FuelLabs/fuel-core#1987]
Fuel-core is running in a Kubernetes cluster with a service configured to map POD’s 30333/TCP+UDP to a NodePort. The container’s startup parameters are set as follows:
```
--enable-p2p
--address=NODE_IP
--peering-port=30333
```
Upon startup, an error occurs, and the error message from the logs (kubectl logs fuel-testnet-0) is:
```
2024-06-25T15:01:21.901812Z  INFO fuel_core_bin::cli::run: 276: Block production disabled
2024-06-25T15:01:21.901849Z  WARN fuel_core_bin::cli::run: 301: The coinbase recipient `ContractId` is not set!
2024-06-25T15:01:21.901856Z  INFO fuel_core_bin::cli::run: 395: Fuel Core version v0.30.0
2024-06-25T15:01:21.901859Z  INFO fuel_core::combined_database: 94: Opening database "/data/db" with cache size "1073741824"
2024-06-25T15:01:21.994320Z  INFO new{name=fuel-sepolia-testnet-node}: fuel_core::service: 200: Initializing database
2024-06-25T15:01:21.994378Z  INFO new{name=fuel-sepolia-testnet-node}: fuel_core::service: 204: Initializing sub services
2024-06-25T15:01:22.002856Z  INFO new{name=fuel-sepolia-testnet-node}: fuel_core::graphql_api::api_service: 247: Binding GraphQL provider to 0.0.0.0:4000
2024-06-25T15:01:22.009365Z  INFO new{name=fuel-sepolia-testnet-node}:initialize_loop{service="FuelService"}: fuel_core_services::service: 321: Starting FuelService service
2024-06-25T15:01:22.009632Z  INFO new{name=fuel-sepolia-testnet-node}:initialize_loop{service="GraphQL"}: fuel_core_services::service: 321: Starting GraphQL service
2024-06-25T15:01:22.009678Z  INFO new{name=fuel-sepolia-testnet-node}:initialize_loop{service="TxPool"}: fuel_core_services::service: 321: Starting TxPool service
2024-06-25T15:01:22.009774Z  INFO new{name=fuel-sepolia-testnet-node}:initialize_loop{service="ConsensusParametersProviderTask"}: fuel_core_services::service: 321: Starting ConsensusParametersProviderTask service
2024-06-25T15:01:22.009980Z  INFO new{name=fuel-sepolia-testnet-node}:initialize_loop{service="GasPriceUpdater"}: fuel_core_services::service: 321: Starting GasPriceUpdater service
2024-06-25T15:01:22.010007Z  INFO new{name=fuel-sepolia-testnet-node}:initialize_loop{service="Relayer"}: fuel_core_services::service: 321: Starting Relayer service
2024-06-25T15:01:22.010245Z  INFO new{name=fuel-sepolia-testnet-node}:initialize_loop{service="P2P"}: fuel_core_services::service: 321: Starting P2P service
2024-06-25T15:01:22.011721Z  INFO new{name=fuel-sepolia-testnet-node}:initialize_loop{service="P2P"}: libp2p_swarm: 367: local_peer_id=16Uiu2HAmBP8gPRKUsVtNy3Nni7vdhjYkBJsZY34KbqiBs2K76fZB
2024-06-25T15:01:22.011762Z  INFO new{name=fuel-sepolia-testnet-node}:initialize_loop{service="P2P"}: fuel_core_p2p::p2p_service: 249: The p2p service starts on the `/ip4/64.38.133.213/tcp/30333` with `16Uiu2HAmBP8gPRKUsVtNy3Nni7vdhjYkBJsZY34KbqiBs2K76fZB`
thread 'tokio-runtime-worker' panicked at /build/crates/services/src/service.rs:325:10:
The initialization of the service failed.:

Caused by:
    0: Cannot assign requested address (os error 99)
    1: Cannot assign requested address (os error 99)
    2: Cannot assign requested address (os error 99)

Stack backtrace:
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
   1: <fuel_core_p2p::service::UninitializedTask<V,fuel_core_p2p::service::SharedState> as fuel_core_services::service::RunnableService>::into_task::{{closure}}
   2: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
   3: tokio::runtime::task::raw::poll
   4: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
   5: tokio::runtime::task::raw::poll
   6: std::sys_common::backtrace::__rust_begin_short_backtrace
   7: core::ops::function::FnOnce::call_once{{vtable.shim}}
   8: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007:9
   9: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007:9
  10: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys/unix/thread.rs:108:17
  11: <unknown>
  12: <unknown>
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
   3: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
   4: tokio::runtime::task::raw::poll
   5: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
   6: tokio::runtime::task::raw::poll
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by zfy0701** [comment]
so basically we need an NAT flag for node running within local network, in geth there is flag like:
```
  --nat value                         NAT port mapping mechanism (any|none|upnp|pmp|extip:<IP>) (default: "any")
```
so you can do 
```
--nat=extip:$EXTERNAL_IP
```
to tell peers to connect with this  IP,

**Comment by wengych** [comment]
Fixed by passing env PUBLIC_ADDRESS
